-- MySQL Script generated by MySQL Workbench
-- Sat May 30 04:15:30 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gaiatools_new
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gaiatools_new
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gaiatools_new` DEFAULT CHARACTER SET utf8 ;
USE `gaiatools_new` ;

-- -----------------------------------------------------
-- Table `gaiatools_new`.`Config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Config` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Config` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `config_setting` VARCHAR(128) NULL DEFAULT NULL,
  `config_value` VARCHAR(1024) NULL DEFAULT NULL,
  `lu_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `insert_timestamp` TIMESTAMP NULL DEFAULT NULL COMMENT 'ideally we would like to use CURRENT_TIMESTAMP as the default, but older MySQL used on the gaiatools server doesn\'t permit multiple uses of the CTS value',
  `user_defined` TINYINT(1) NULL DEFAULT '1',
  `default_value` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `IXU01_CONFIG` (`config_setting` ASC),
  UNIQUE INDEX `ixu01_config_setting` (`config_setting` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Role` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(80) NOT NULL,
  `role_description` VARCHAR(255) NOT NULL,
  `role_level` INT(11) NOT NULL DEFAULT '1',
  `lu_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lu_user` VARCHAR(25) NOT NULL,
  `insert_timestamp` TIMESTAMP NULL DEFAULT NULL COMMENT 'ideally we would like to use CURRENT_TIMESTAMP as the default, but older MySQL used on the gaiatools server doesn\'t permit multiple uses of the CTS value',
  `user_defined` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`role_id`),
  INDEX `IXU01_role_name` (`role_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`User` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `registered` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dob` DATE NOT NULL,
  `salt` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `lu_password` TIMESTAMP NULL DEFAULT NULL,
  `banned` TINYINT(1) NULL DEFAULT '0',
  `last_login_ip` VARCHAR(45) NULL,
  `last_login_time` VARCHAR(45) NULL,
  `login_failed_attempts` INT(11) NULL DEFAULT '0',
  `account_locked` TINYINT(1) NOT NULL DEFAULT '0',
  `timezone` VARCHAR(30) NULL,
  `Role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `Salt_UNIQUE` (`salt` ASC),
  INDEX `fk_Users_Roles1_idx` (`Role_id` ASC),
  CONSTRAINT `fk_Users_Roles1`
    FOREIGN KEY (`Role_id`)
    REFERENCES `gaiatools_new`.`Role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 141
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Gaia_Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Gaia_Account` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Gaia_Account` (
  `gaia_id` INT(11) NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  `avatar` VARCHAR(80) NULL DEFAULT NULL,
  `user_level` INT(11) NOT NULL DEFAULT '8',
  `filter_level` INT(11) NULL DEFAULT NULL,
  `avatar_url` VARCHAR(120) NOT NULL,
  `account_age` INT(11) NULL DEFAULT NULL,
  `gender` VARCHAR(6) NULL DEFAULT NULL,
  `last_updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`gaia_id`),
  INDEX `fk_Gaia_Accounts_Users1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Gaia_Accounts_Users1`
    FOREIGN KEY (`User_id`)
    REFERENCES `gaiatools_new`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Gaia_Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Gaia_Item` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Gaia_Item` (
  `id` INT(11) NOT NULL,
  `sex` VARCHAR(6) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `sub_type` VARCHAR(45) NULL DEFAULT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `thumbnail` VARCHAR(100) NOT NULL,
  `thumbfile` VARCHAR(100) NULL DEFAULT NULL,
  `price` INT(11) NULL DEFAULT NULL,
  `gpass` INT(11) NULL DEFAULT NULL,
  `store_id` VARCHAR(45) NULL DEFAULT NULL,
  `store_ignore` VARCHAR(45) NULL DEFAULT NULL,
  `last_updated` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Gaia_Account_has_Gaia_Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Gaia_Account_has_Gaia_Item` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Gaia_Account_has_Gaia_Item` (
  `Gaia_Account_gaia_id` INT(11) NOT NULL,
  `Gaia_Item_id` INT(11) NOT NULL,
  PRIMARY KEY (`Gaia_Account_gaia_id`, `Gaia_Item_id`),
  INDEX `fk_Gaia_Accounts_has_Gaia_Items_Gaia_Items1_idx` (`Gaia_Item_id` ASC),
  INDEX `fk_Gaia_Accounts_has_Gaia_Items_Gaia_Accounts1_idx` (`Gaia_Account_gaia_id` ASC),
  CONSTRAINT `fk_Gaia_Accounts_has_Gaia_Items_Gaia_Accounts1`
    FOREIGN KEY (`Gaia_Account_gaia_id`)
    REFERENCES `gaiatools_new`.`Gaia_Account` (`gaia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gaia_Accounts_has_Gaia_Items_Gaia_Items1`
    FOREIGN KEY (`Gaia_Item_id`)
    REFERENCES `gaiatools_new`.`Gaia_Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Image_Map`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Image_Map` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Image_Map` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image_url` TEXT NOT NULL,
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Image_Map_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Image_Map_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `gaiatools_new`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`News`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`News` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`News` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(160) NOT NULL,
  `locale` VARCHAR(5) NOT NULL DEFAULT 'en_US',
  `title` VARCHAR(80) NOT NULL,
  `byline` VARCHAR(255) NOT NULL,
  `shortTitle` VARCHAR(80) NULL DEFAULT NULL,
  `teaser` VARCHAR(255) NULL DEFAULT NULL,
  `body` TEXT NULL DEFAULT NULL,
  `release_timestamp` TIMESTAMP NULL DEFAULT NULL,
  `lu_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `insert_timestamp` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `IXU01_NEWS_SLUG` (`slug` ASC),
  INDEX `IXN01_NEWS_LUT` (`lu_timestamp` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Quest_Bar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Quest_Bar` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Quest_Bar` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `thumbnail` VARCHAR(100) NOT NULL,
  `goal` BIGINT(8) NOT NULL,
  `current` BIGINT(8) NOT NULL,
  `User_id` INT(11) NOT NULL,
  `Gaia_Item_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Quest_Bars_Users1_idx` (`User_id` ASC),
  INDEX `fk_Quest_Bars_Gaia_Items1_idx` (`Gaia_Item_id` ASC),
  CONSTRAINT `fk_Quest_Bars_Gaia_Items1`
    FOREIGN KEY (`Gaia_Item_id`)
    REFERENCES `gaiatools_new`.`Gaia_Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quest_Bars_Users`
    FOREIGN KEY (`User_id`)
    REFERENCES `gaiatools_new`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Random_Image_Gen_Set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Random_Image_Gen_Set` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Random_Image_Gen_Set` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Random_Image_Set_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Random_Image_Set_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `gaiatools_new`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Random_Image_Gen_Url`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Random_Image_Gen_Url` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Random_Image_Gen_Url` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image_url` TEXT NOT NULL,
  `RIG_Set_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RIG_Url_Random_Image_Set1_idx` (`RIG_Set_id` ASC),
  CONSTRAINT `fk_RIG_Url_Random_Image_Set1`
    FOREIGN KEY (`RIG_Set_id`)
    REFERENCES `gaiatools_new`.`Random_Image_Gen_Set` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Category` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `parent_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `IXU01_THEME_CTGRY_TITLE` (`title` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Theme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Theme` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Theme` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `title` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `publish` TINYINT(1) NOT NULL DEFAULT '1',
  `private` TINYINT(1) NOT NULL DEFAULT '0',
  `featured` TINYINT(1) NOT NULL DEFAULT 0,
  `featured_date` TIMESTAMP NULL,
  `description` VARCHAR(180) NULL DEFAULT NULL,
  `rating` DECIMAL(2,1) NULL,
  `template` VARCHAR(7) NOT NULL DEFAULT 'classic',
  `basetheme` VARCHAR(7) NULL DEFAULT NULL,
  `friendstyle` VARCHAR(7) NULL DEFAULT NULL,
  `commentstyle` VARCHAR(7) NULL DEFAULT NULL,
  `code` BLOB NOT NULL,
  `shopurl` TEXT NULL DEFAULT NULL,
  `snapshot` VARCHAR(75) NULL DEFAULT NULL,
  `lu_timestamp` TIMESTAMP NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `lu_ip` VARCHAR(45) NULL DEFAULT NULL,
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Themes_Users_idx` (`User_id` ASC),
  CONSTRAINT `fk_Themes_Users`
    FOREIGN KEY (`User_id`)
    REFERENCES `gaiatools_new`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Theme_Reivew`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Theme_Reivew` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Theme_Reivew` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rating` DECIMAL(2,1) NOT NULL,
  `message` VARCHAR(180) NOT NULL,
  `Theme_User_id` INT(11) NOT NULL,
  `Theme_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Theme_Reivews_Themes1_idx` (`Theme_id` ASC),
  CONSTRAINT `fk_Theme_Reivews_Themes1`
    FOREIGN KEY (`Theme_id`)
    REFERENCES `gaiatools_new`.`Theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Tag` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `parent_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Title_UNIQUE` (`title` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 83
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Theme_has_Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Theme_has_Tag` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Theme_has_Tag` (
  `Theme_id` INT(11) NOT NULL,
  `Tag_id` INT(11) NOT NULL,
  PRIMARY KEY (`Theme_id`, `Tag_id`),
  INDEX `fk_Themes_has_Theme_Tags_Themes1_idx` (`Theme_id` ASC),
  INDEX `fk_Themes_has_Theme_Tags_Tags1_idx` (`Tag_id` ASC),
  CONSTRAINT `fk_Themes_has_Theme_Tags_Themes1`
    FOREIGN KEY (`Theme_id`)
    REFERENCES `gaiatools_new`.`Theme` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Themes_has_Theme_Tags_Theme_Tags1`
    FOREIGN KEY (`Tag_id`)
    REFERENCES `gaiatools_new`.`Tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`ci_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`ci_sessions` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`ci_sessions` (
  `id` VARCHAR(40) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ci_sessions_timestamp` (`timestamp` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Theme_has_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Theme_has_Category` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Theme_has_Category` (
  `Theme_id` INT(11) NOT NULL,
  `Category_id` INT(11) NOT NULL,
  PRIMARY KEY (`Theme_id`, `Category_id`),
  INDEX `fk_Themes_has_Theme_Categories_Theme_Categories1_idx` (`Category_id` ASC),
  INDEX `fk_Themes_has_Theme_Categories_Themes1_idx` (`Theme_id` ASC),
  CONSTRAINT `fk_Themes_has_Theme_Categories_Themes1`
    FOREIGN KEY (`Theme_id`)
    REFERENCES `gaiatools_new`.`Theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Themes_has_Theme_Categories_Theme_Categories1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `gaiatools_new`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Alert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Alert` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Alert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` VARCHAR(45) NOT NULL,
  `enable_date` DATETIME NOT NULL,
  `disable_disable` DATETIME NOT NULL,
  `force_active` TINYINT(1) NOT NULL DEFAULT 0,
  `message` BLOB NOT NULL,
  `alert_level` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`User_Ip_Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`User_Ip_Login` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`User_Ip_Login` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(45) NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ip_Logins_Users1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Ip_Logins_Users1`
    FOREIGN KEY (`User_id`)
    REFERENCES `gaiatools_new`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Nav_Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Nav_Group` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Nav_Group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `abbr` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Navigation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Navigation` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Navigation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NOT NULL,
  `uri` VARCHAR(255) NULL,
  `target` VARCHAR(10) NULL,
  `position` VARCHAR(45) NULL,
  `parent_id` VARCHAR(45) NULL,
  `is_parent` TINYINT(1) NOT NULL DEFAULT 0,
  `class` VARCHAR(255) NULL,
  `visible` TINYINT(1) NOT NULL DEFAULT 0,
  `Role_role_id` INT(11) NOT NULL,
  `Nav_Group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Navigation_Role1_idx` (`Role_role_id` ASC),
  INDEX `fk_Navigation_Nav_Group1_idx` (`Nav_Group_id` ASC),
  CONSTRAINT `fk_Navigation_Role1`
    FOREIGN KEY (`Role_role_id`)
    REFERENCES `gaiatools_new`.`Role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Navigation_Nav_Group1`
    FOREIGN KEY (`Nav_Group_id`)
    REFERENCES `gaiatools_new`.`Nav_Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gaiatools_new`.`Wix_Url`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gaiatools_new`.`Wix_Url` ;

CREATE TABLE IF NOT EXISTS `gaiatools_new`.`Wix_Url` (
  `id` INT NOT NULL,
  `created` TIMESTAMP NOT NULL,
  `url` VARCHAR(2083) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
